# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'libmgmt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 70, 791, 521))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.username = QtWidgets.QLineEdit(self.login_page)
        self.username.setGeometry(QtCore.QRect(322, 70, 161, 21))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.login_page)
        self.password.setGeometry(QtCore.QRect(322, 130, 161, 21))
        self.password.setObjectName("password")
        self.login_btn = QtWidgets.QPushButton(self.login_page)
        self.login_btn.setGeometry(QtCore.QRect(340, 180, 113, 32))
        self.login_btn.setObjectName("login_btn")
        self.register_link = QtWidgets.QCommandLinkButton(self.login_page)
        self.register_link.setGeometry(QtCore.QRect(310, 240, 193, 41))
        self.register_link.setObjectName("register_link")
        self.stackedWidget.addWidget(self.login_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.username_reg = QtWidgets.QLineEdit(self.register_page)
        self.username_reg.setGeometry(QtCore.QRect(350, 30, 113, 21))
        self.username_reg.setObjectName("username_reg")
        self.password_reg = QtWidgets.QLineEdit(self.register_page)
        self.password_reg.setGeometry(QtCore.QRect(350, 90, 113, 21))
        self.password_reg.setObjectName("password_reg")
        self.label_2 = QtWidgets.QLabel(self.register_page)
        self.label_2.setGeometry(QtCore.QRect(380, 150, 60, 16))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.register_page)
        self.radioButton.setGeometry(QtCore.QRect(310, 180, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.register_page)
        self.radioButton_2.setGeometry(QtCore.QRect(440, 180, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox = QtWidgets.QComboBox(self.register_page)
        self.comboBox.setGeometry(QtCore.QRect(360, 250, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.register_page)
        self.label_3.setGeometry(QtCore.QRect(380, 220, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.register_page)
        self.label_4.setGeometry(QtCore.QRect(370, 310, 81, 16))
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.register_page)
        self.checkBox.setGeometry(QtCore.QRect(290, 340, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.register_page)
        self.checkBox_2.setGeometry(QtCore.QRect(410, 340, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.register_page)
        self.checkBox_3.setGeometry(QtCore.QRect(540, 340, 87, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.register_btn = QtWidgets.QPushButton(self.register_page)
        self.register_btn.setGeometry(QtCore.QRect(350, 390, 113, 32))
        self.register_btn.setObjectName("register_btn")
        self.login_link = QtWidgets.QCommandLinkButton(self.register_page)
        self.login_link.setGeometry(QtCore.QRect(350, 440, 193, 41))
        self.login_link.setObjectName("login_link")
        self.stackedWidget.addWidget(self.register_page)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.register_link.clicked.connect(MainWindow.navigate_register)
        self.login_link.clicked.connect(MainWindow.navigate_login)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.password.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.register_link.setText(_translate("MainWindow", "New User ? Register Here"))
        self.label_2.setText(_translate("MainWindow", "Gender"))
        self.radioButton.setText(_translate("MainWindow", "Male"))
        self.radioButton_2.setText(_translate("MainWindow", "Female"))
        self.label_3.setText(_translate("MainWindow", "Country"))
        self.label_4.setText(_translate("MainWindow", "Preferences"))
        self.checkBox.setText(_translate("MainWindow", "Travel"))
        self.checkBox_2.setText(_translate("MainWindow", "Shopping"))
        self.checkBox_3.setText(_translate("MainWindow", "Sports"))
        self.register_btn.setText(_translate("MainWindow", "Register"))
        self.login_link.setText(_translate("MainWindow", "Go to login"))
        self.label.setText(_translate("MainWindow", "Library Management"))

